swiftmailer:
    #    url: '%env(MAILER_URL)%'
    username: powiadomienia@commit-m.pl
    password: MJuMdizweXRByD0YzvDe
    host: smtp.commit-m.pl
    port: 587
    transport: smtp
    encryption: tls
    auth_mode: plain
    spool:
        type: file
        path: '%kernel.project_dir%/var/spool'
    stream-options:
        ssl:
            allow_self_signed : true
            verify_peer: false
            verify_peer_name: false
