ef_connect:
  path:  /admin/efconnect/{instance}/{homeFolder}
  defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::load, instance: default, homeFolder: '' }
ef_main_js:
  path:  /admin/elfinder.main.js
  defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::mainJS }
#  defaults: { _controller: App\Controller\Admin\ElfinderController::mainJS }

elfinder:
  path: /admin/elfinder/{instance}/{homeFolder}
  defaults: { _controller: FM\ElfinderBundle\Controller\ElFinderController::show, instance: default, homeFolder: '' }
